<?php

// print_r($editproduct);
$data = $editproduct;
$additionals = $data[0];
$variations = $data[1];

$label = $additionals['label'];
$value = $additionals['value'];
$variation_field = $variations['Variation Field'];
$variation_name = $variations['Variation Name'];
$variation_price = $variations['Variation Price'];
$size = $variations['size'];
// echo '<pre>';
// print_r($variation_price);


?>

<div class="editproduct w-50 m-auto">
    <h1>Edit Product</h1>
    <form action="/products/update" method="post">
    <input type="text" value="<?php echo $data['name']; ?>" class="form-control" name="product_name">
    <input type="text" value="<?php echo $data['category']; ?>" class="form-control" name="product_category">
    <input type="text" value="<?php echo $data['price']; ?>" class="form-control" name="product_price">
    <input type="text" value="<?php echo $data['stock']; ?>" class="form-control" name="product_stock">

<table class="table table-striped">
    <?php
    if ($label) { 
    for ($i=0; $i<count($label); $i++) { ?>
        <tr>      
            <td><input type="text" value="<?php echo $label[$i]; ?>" name="label[]"> </td>
            <td><input type="text" value="<?php echo $value[$i]; ?>" name="value[]"> </td>
        </tr>       
    <?php } 
    } ?>   
    
<?php
    if ($variation_field) { 
        
    for ($i=0; $i<count($variation_field); $i++) { ?>
        <tr>      
            <td><input type="text" value="<?php echo $variation_field[$i]; ?>" name="variation_field[]"> </td>
            <td><input type="text" value="<?php echo $variation_name[$i]; ?>" name="variation_name[]"> </td>
            <td><input type="text" value="<?php echo $variation_price[$i]; ?>" name="variation_price[]"> </td>
        </tr>       
    <?php } 
    } ?> 
</table>
<div class="d-flex justify-content-center">
    <input type="hidden" name="id" value="<?php echo $this->request->getQuery('id'); ?>" >
    <input type="submit" value="Update" class="btn btn-success px-5">
</div>
</form>
</div>