
<div class="header d-flex justify-content-around mt-2">
    <a href="/products/add">Add Product</a>
<br>
    <input type="text" id="searchValue" onkeyup="search()"  placeholder="Search for names.." title="Type in a name" class="form-control w-50">

</div>


<h1 class="text-center my-5">Products</h1>

<table class="table table-striped" id="myTable">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Categegory</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Actions</th>
        <th>Explore</th>
    </tr>

<?php foreach ($products as $key) { ?>
    <tr id="productRow">
        <td><?php echo $key['_id']; ?></td>
        <td><?php echo $key['name']; ?></td>
        <td><?php echo $key['category']; ?></td>
        <td><?php echo $key['price']; ?> ₹</td>
        <td><?php echo $key['stock']; ?></td>
        <td><a href="/products/edit?id=<?php echo $key['_id']; ?>" class="text-info"> Edit</a> 
        <a href="/products/delete?id=<?php echo $key['_id']; ?>" class="text-danger mx-2"> Delete </a></td>     
        <td><input type = "submit" class = "btn btn-primary" data-id = "<?php echo $key['_id'] ?>" value = "View More" id = "show_popup"></td>
    </tr>

<?php }?>    
</table>

<div id="popup" class="w-75 bg-dark text-light" style="position: absolute; top:15%; left:12.5%; height:400px; opacity:0.8;">
<div class="d-flex justify-content-end">
    <a  id = "close" class="text-light btn btn-danger">X</a>
</div>

<div id="data" class="w-50 m-auto">

</div>
</div>
<?php
//  echo $oneproduct['name'];

?>
</div>

