<?php

?>

<a style="position:relative; top:5%" href="/products/view">Show Products</a>

<div class="main row py-5">
   
    <form action="/products/add" method="post" class="d-flex col sm-4 md-4">

            <div class="additional my-5 mx-3 col sm-4 md-4">
            <a class="btn btn-outline-danger text-dark" id="additional_fields" >Addition Field</a>
            <div id="new" class="mt-4">
            </div>
            </div>

            <div class="form col sm-4 md-4">
            <h1 class="text-center">Add New Order</h1>
            <input type="text" name="product_name" placeholder="Product Name*" class="form-control my-3" required>
            <input type="text" name="product_category" placeholder="Product Categegory*" class="form-control my-3" required>
            <input type="text" name="product_price" placeholder="Product Price*" class="form-control my-3" required>
            <input type="text" name="product_stock" placeholder="Product Stock*" class="form-control my-3" required>
            <div class="submit d-flex justify-content-center">
                <input type="submit" value="Add Product" class="btn btn-primary">
            </div>
            </div>
            
            
            <!-- <div class="variations my-5 mx-3 col sm-4 md-4">
              
           
            <a class="btn btn-outline-danger text-dark" id="variations">New Variation</a>
            <div id="new_variation" class="mt-4">
                
            </div>
            </div> -->

            <!-- <div class="col md-4">
            <a class="btn btn-outline-danger text-dark" id="create_new_variation">New Variation</a>
            <div id="show_variations"> -->
                
            </div>

            <!-- </div> -->
        </form>
    </div>
</div>
</div>

